### ISSUE TITLE
Dokumentácia návrhu grafického designu aplikácie

### ISSUE THREAD

**Issue by lexendo** [TIS2024-FMFI/drony#20]
Je potrebné vytvoriť dokumentáciu k návrhu grafického dizajnu aplikácie, ktorá popíše jednotlivé prvky dizajnu a ich fungovanie z používateľského pohľadu. 
Dokumentácia bude slúžiť na objasnenie rozloženia, funkčnosti a interakcie v aplikácii. 
Tento dokument nám pomôže počas vývoja a uľahčí koordináciu medzi dizajnom a implementáciou.

**Comment by lexendo** [comment]
Dokumentácia designu kompletná.

[Design_Documentation_Drones.pdf](https://github.com/user-attachments/files/17534146/Design_Documentation_Drones.pdf)
[Dokumentácia návrhu dizajnu aplikácie.docx](https://github.com/user-attachments/files/17534147/Dokumentacia.navrhu.dizajnu.aplikacie.docx)

**Comment by lexendo** [comment]
[Dokumentacia.navrhu.dizajnu.aplikacie.docx](https://github.com/user-attachments/files/17612523/Dokumentacia.navrhu.dizajnu.aplikacie.docx)
[Dokumentacia.navrhu.dizajnu.aplikacie.pdf](https://github.com/user-attachments/files/17612522/Dokumentacia.navrhu.dizajnu.aplikacie.pdf)

**Comment by tyoma-ka** [comment]
Bolo by dobre pridat obrazky grafickeho designu (napr. screenshoty) potom do navrhu

**Comment by tyoma-ka** [comment]
A potom mozno bolo by fajn este pridat tlacidlo ⏹️, ktore stopne animaciu a prejde na zaciatok

**Comment by lexendo** [comment]
Áno, tie obrazky pridam len som to ešte trochu predesignoval
To stop tlačidlo je aktuálne v sidepaneli, ale movnem ho vedľa play buttonu a vymažem rewind a fast forward

**Comment by lexendo** [comment]
[Dokumentacia_dizajnu.docx](https://github.com/user-attachments/files/17706515/Dokumentacia_dizajnu.docx)
[Dokumentacia_dizajnu.pdf](https://github.com/user-attachments/files/17706516/Dokumentacia_dizajnu.pdf)
