### ISSUE TITLE
Rozhodnúť akú Render Pipeline využijeme

### ISSUE THREAD

**Issue by lexendo** [TIS2024-FMFI/drony#21]
Built-in Pipeline: 
Vhodný pre široké spektrum zariadení, stabilný a kompatibilný so staršími assetmi. Ak je projekt jednoduchý a má bežať na väčšom množstve zariadení (napr. mobily, web), môže byť vhodný.

URP (Universal Render Pipeline): 
Lepší pre optimalizáciu a multiplatformové použitie, napríklad ak cieľujete mobilné a menej výkonné zariadenia.

HDRP (High Definition Render Pipeline): 
Pre aplikácie s náročnou grafikou a pokročilými vizuálnymi efektmi, ale vyžaduje vysoký výkon, takže sa hodí najmä pre PC alebo konzoly.

**Comment by tyoma-ka** [comment]
Zvolili sme Universal Render Pipeline
