### ISSUE TITLE
Vytvorenie designu SidePanelu v Unity

### ISSUE THREAD

**Issue by lexendo** [TIS2024-FMFI/drony#39]
Treba vytvorit sidepanel (ktory bol nadizajnovany) v unity, aby sme mohli na neho implementovat dalsie features.

**Comment by lexendo** [comment]
![obrázok](https://github.com/user-attachments/assets/764f92cd-0d70-4308-8871-50620bbdf63c)
velka cast panelu (z hladiska vizualu) vytvorena pomocou UI toolkitu

**Comment by tyoma-ka** [comment]
Vyzera velmi cool. Potom este pozriem ten kod, ale zatial sa mi zda, ze je to velmi dobre 👍🎉
