### ISSUE TITLE
Pridať funkcionalitu nahrávania súborov

### ISSUE THREAD

**Issue by lexendo** [TIS2024-FMFI/drony#40]
Potrebujeme implementovať funkcionalitu, ktorá umožní používateľovi nahrať súbor cez systémový súborový prehliadač, napríklad po kliknutí na tlačidlo Upload Command File.

**Comment by tyoma-ka** [comment]
Nice 🤩🤌

**Comment by tyoma-ka** [comment]
A ten subor niekde skopiruje do adresaru projektu alebo proste bude drzat referenciu na neho?

**Comment by faresur** [comment]
Cool! Vyzera dobre!

**Comment by lexendo** [comment]
> A ten subor niekde skopiruje do adresaru projektu alebo proste bude drzat referenciu na neho?

Mozme spravit v ProcessFile(string path) funkcii oboje, zatial ani jedno :D 

aktualne to len pri button clicku otvori folder browser, tam si vyberies txt file a ulozi to do filePath cestu v tvojom pc k tomu textaku.
Potom callne sa ProcessFile(string path) ktora zatial nic nerobi

**Comment by tyoma-ka** [comment]
Aha, okay, dobre. Diki za info!
