### ISSUE TITLE
Implementovať triedu na rozdelenie Command súboru a volanie ConfigInterpreter a FlightProgramInterpreter

### ISSUE THREAD

**Issue by lexendo** [TIS2024-FMFI/drony#42]
Je potrebné vytvoriť triedu, ktorá spracuje celý Command súbor, oddelí config časť od časti s príkazmi pre drony, a potom zavolá príslušné parsre na spracovanie oboch častí.

Úloha:

    Vytvoriť triedu (napr. CommandFilePreprocessor), ktorá načíta obsah Command súboru.
    Oddeliť config časť od drone commandov – určiť, kde sa nachádza rozdelenie medzi týmito časťami.
    Riadky patriace do config časti by mali byť poslané do ConfigInterpreter.cs.
    Zvyšok súboru (po rozdelení) by mal byť poslaný do FlightProgramInterpreter.cs na spracovanie príkazov pre drony.

**Comment by tyoma-ka** [comment]
@faresur , asi ty to ides implementovat, tak trosku upresnim issue:
```
CommandFilePreprocessor (alebo CommandFileSplitter) uz dostane na vstup string (obsah suboru), a jeho ciel je vratit dvojicu:
List<string> - zoznam riadkov pre config cast
List<string> - zoznam riadkov pre drone commandy
```
