### ISSUE TITLE
fix sidepanel visual bug

### ISSUE THREAD

**Issue by lexendo** [TIS2024-FMFI/drony#46]
Z nejakeho dovodu sa sidepanel nezobrazuje vsetkym  vizualne dobre, musim prist na to ze preco a opravit

**Comment by tyoma-ka** [comment]
Hej. A treba pozriet, ci nie je to len kvoli tomu, ze ja mam MacOS, takze mi to zle zobrazuje

**Comment by lexendo** [comment]
je to zrejme kvoli velkosti screenu pri inicializacii, pre velke obrazovky to je dobre pre mensie ntb sa to trochu kazi, spravim to nejak mudrejsie responzivne
