### ISSUE TITLE
Standalone files browser bug

### ISSUE THREAD

**Issue by lexendo** [TIS2024-FMFI/drony#47]
Standalone files browser zrejme aktualne nefunguje pre mac devices, treba sa do toho pozriet a zistit ci je mozne to opravit v ramci toho extensionu

**Comment by tyoma-ka** [comment]
Fixol som bug. Problem bol z tym, ze kniznica StandaloneFileBrowser nepodporovala moj Apple Silicon chip. lol. Takze nasiel som nejaku verziu tej kniznici, v ktorej to fixli. Zatial commitnem to v "fix_Timing_in_Trajectory_Generator" a potom ked ostatni skontroluju, ze im to ide, tak pushnem

**Comment by tyoma-ka** [comment]
https://github.com/user-attachments/assets/6b35ba5f-9f03-48ed-9e58-fa7c65dc37d1
