### ISSUE TITLE
2. stretnutie s cvičiacim 

### ISSUE THREAD

**Issue by faresur** [TIS2024-FMFI/drony#6]
Datum: 15. 10. 2024 20:00

**Comment by tyoma-ka** [comment]
## Treba sa dozviedet na cviceni, ci mozeme mat stretntie online

## Na stretnurii treba sa spytat nasledujuce otazky:
* Ci je nejaka potreba nieco upravovat v katalogu poziadaviek
* Ak nieco mame upravit, tak dokedy to mozeme spravit
* Co vsetko mame navrhnut v nasem systeme
* Ci treba nam mat nejaku komunikaciu zo serverom
* Kedy budeme mat poslat prvu verziu navrha
